### ISSUE TITLE
[BUG] - Missing return and context

### ISSUE THREAD

**Issue by ws265660** [ws268644/ProjectChocobo#20]
**Describe the bug**
I merged dp_eventUpdate to Feature_EventUpdate, but the issue is that there seems to be no return and missing connections to the database.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
The function should return the details for an event.

**Actual behaviour**
The feature lacks a return so gives an error

**Screenshots**
![image](https://user-images.githubusercontent.com/34048357/160929835-0999d966-9028-44d2-9edd-4f938882c76b.png)

**Additional context**
It seems like there should be more before the return.

**Comment by Auragen-dev** [comment]
I hadn't finished that function.
I just finished it now if you want to re-merge it

**Comment by ws265660** [comment]
Will do
